complete -c post-review -f -a '- --' -n 'test (commandline --current-token) != -'
complete -c post-review -f -l 'version' --description "Show version number and exit"
complete -c post-review -f -s h -l 'help' --description "Show this help message and exit"
complete -c post-review -f -s p -l 'publish' --description "Publish review request immediately"
complete -c post-review -x -s r -l 'review-request-id' --description "Existing review request ID to update"
complete -c post-review -f -s o -l 'open' --description "Open a web browser to the review request page"
complete -c post-review -f -s n -l 'output-diff' --description "Output diff to the console and exit"
complete -c post-review -x -l 'server' --description "ReviewBoard server to use"
complete -c post-review -f -l 'disable-proxy' --description "Prevent requests from going through a proxy server"
complete -c post-review -f -l 'all-changes' --description "Upload new diff and update review info from changelist"
complete -c post-review -f -l 'reopen' --description "Reopen discarded review request after update"
complete -c post-review -x -s u -l 'target-groups' --description "Groups to perform the review"
complete -c post-review -x -s i -l 'target-people' --description "People to perform the review"
complete -c post-review -x -l 'summary' --description "Summary of the review"
complete -c post-review -x -l 'description' --description "Description of the review"
complete -c post-review -r -l 'description-file' --description "Text file containing description of the review"
complete -c post-review -f -s g -l 'guess-fields' --description "Equivalent to --guess-summary --guess-description"
complete -c post-review -f -l 'guess-summary' --description "Guess summary from the latest commit"
complete -c post-review -f -l 'no-package-name-in-summary' --description "Omit package name prefix from the summary"
complete -c post-review -f -l 'guess-description' --description "Guess description based on commits in this branch"
complete -c post-review -x -l 'testing-done' --description "Details of testing done"
complete -c post-review -r -l 'testing-done-file' --description "Text file containing details of testing done"
complete -c post-review -x -l 'branch' --description "Affected branch"
complete -c post-review -x -l 'bugs-closed' --description "List of bugs closed"
complete -c post-review -x -l 'change-description' --description "Description of changes in this revision of the review"
complete -c post-review -x -l 'revision-range' --description "Generate diff based on a revision range"
complete -c post-review -x -l 'submit-as' --description "Username for author of the review"
complete -c post-review -x -l 'username' --description "Username for ReviewBoard server"
complete -c post-review -x -l 'password' --description "Password for ReviewBoard server"
complete -c post-review -f -l 'change-only' --description "Update info from changelist but don't upload new diff"
complete -c post-review -f -l 'snapshot' --description "Create a snapshot and base review on it"
complete -c post-review -x -l 'parent' --description "Parent branch to diff against"
complete -c post-review -x -l 'tracking-branch' --description "Tracking branch (git only)"
complete -c post-review -x -l 'p4-client' --description "Perforce client name"
complete -c post-review -x -l 'p4-port' --description "Perforce server's IP address"
complete -c post-review -x -l 'p4-passwd' --description "Perforce password or ticket"
complete -c post-review -x -l 'svn-changelist' --description "Generate diff based on a local SVN changelist"
complete -c post-review -x -l 'repository-url' --description "Origin url for repository outside of working copy"
complete -c post-review -f -s d -l 'debug' --description "Display debug output"
complete -c post-review -f -l 'extra-debug' --description "Display verbose debug output"
complete -c post-review -r -l 'diff-filename' --description "Upload an existing diff file"
complete -c post-review -x -l 'http-username' --description "Username for HTTP Basic authentication"
complete -c post-review -x -l 'http-password' --description "Password for HTTP Basic authentication"
complete -c post-review -x -l 'basedir' --description "Override repository absolute path for diff generation"
complete -c post-review -f -l 'skip-pinocchio' --description "Skip infosec checks for credentials in diff"
complete -c post-review -f -l 'no-review-guess' --description "Don't update the existing review"
complete -c post-review -f -l 'note' --description "Append code review URL to first commit"
complete -c post-review -f -l 'setup-crv' --description "Append code review URL to the latest commit"
complete -c post-review -x -s t -l 'target-repo' --description "Target package for multi-package reviews"
complete -c post-review -r -s a -l 'arbitrary-diff' --description "Upload an arbitrary diff file"
complete -c post-review -x -s R -l 'random-reviewers' --description "Randomly selected reviewers"
complete -c post-review -f -l 'pull-request' --description "Enable pull requests"
complete -c post-review -f -l 'no-pull-request' --description "Disable pull requests"
complete -c post-review -f -l 'i18n' --description "Perform i18n scan"
